import type { Client } from '../../types'

const users = {
  u1: { id: 'u1', name: 'Admin User' },
  u2: { id: 'u2', name: 'Sarah Connor' },
  u3: { id: 'u3', name: 'Mike Taylor' },
}

export const getClientsTestApi = async (): Promise<Client[]> => {
  return Promise.resolve([
    {
      id: '1',
      name: 'John Doe',
      email: 'john@mail.com',
      phone: '+380000000000',
      status: 'new',
      comment: 'First contact',
      notes: [
        { id: '1', content: 'mdewd,ekwdneuwn cuwen cunweuicnewuicbw' },
        { id: '2', content: 'dnuewbdybwe dcewybc eywbcu ewcybew ucbew bcyw be' },
      ],
      orderIndex: '1',
      createdBy: users.u1,
      createdAt: new Date().toISOString(),
    },
    {
      id: '2',
      name: 'Jane Smith',
      email: 'jane@mail.com',
      phone: '+380000000001',
      status: 'in_progress',
      comment: 'Waiting for reply',
      orderIndex: '2',
      createdBy: users.u1,
      createdAt: new Date().toISOString(),
    },
    {
      id: '3',
      name: 'Michael Brown',
      email: 'michael@mail.com',
      phone: '+380000000002',
      status: 'done',
      comment: 'Deal closed',
      orderIndex: '3',
      createdBy: users.u2,
      createdAt: new Date().toISOString(),
    },
    {
      id: '4',
      name: 'Emily Johnson',
      email: 'emily@mail.com',
      phone: '+380000000003',
      status: 'new',
      comment: 'Requested demo',
      orderIndex: '4',
      createdBy: users.u2,
      createdAt: new Date().toISOString(),
    },
    {
      id: '5',
      name: 'Daniel Wilson',
      email: 'daniel@mail.com',
      phone: '+380000000004',
      status: 'in_progress',
      comment: 'Negotiation stage',
      orderIndex: '5',
      createdBy: users.u3,
      createdAt: new Date().toISOString(),
    },
    {
      id: '6',
      name: 'Olivia Martinez',
      email: 'olivia@mail.com',
      phone: '+380000000005',
      status: 'new',
      comment: 'Left contact form',
      orderIndex: '6',
      createdBy: users.u3,
      createdAt: new Date().toISOString(),
    },
    {
      id: '7',
      name: 'William Anderson',
      email: 'william@mail.com',
      phone: '+380000000006',
      status: 'done',
      comment: 'Signed contract',
      orderIndex: '7',
      createdBy: users.u1,
      createdAt: new Date().toISOString(),
    },
    {
      id: '8',
      name: 'Sophia Lee',
      email: 'sophia@mail.com',
      phone: '+380000000007',
      status: 'in_progress',
      comment: 'Preparing proposal',
      orderIndex: '8',
      createdBy: users.u2,
      createdAt: new Date().toISOString(),
    },
    {
      id: '9',
      name: 'James Walker',
      email: 'james@mail.com',
      phone: '+380000000008',
      status: 'new',
      comment: 'Cold lead',
      orderIndex: '9',
      createdBy: users.u3,
      createdAt: new Date().toISOString(),
    },
    {
      id: '10',
      name: 'Isabella Harris',
      email: 'isabella@mail.com',
      phone: '+380000000009',
      status: 'done',
      comment: 'Repeat client',
      orderIndex: '10',
      createdBy: users.u1,
      createdAt: new Date().toISOString(),
    },
  ])
}
