import type { Client } from '../../types'

export const getClientsTestApi = async (): Promise<Client[]> => {
  return Promise.resolve([
    {
      id: '1',
      name: 'John Doe',
      email: 'john@mail.com',
      phone: '+380000000000',
      status: 'new',
      comment: 'First contact',
      notes: [
        { id: '1', content: 'mdewd,ekwdneuwn cuwen cunweuicnewuicbw' },
        { id: '2', content: 'dnuewbdybwe dcewybc eywbcu ewcybew ucbew bcyw be' },
        { id: '3', content: 'edbwebdwev ed we dvew dvwev dytwev cxyvew t' },
        { id: '4', content: 'edbwebdwev ed we dvew dvwev dytwev cxyvew t' },
        { id: '5', content: 'edbwebdwev ed we dvew dvwev dytwev cxyvew t' },
        { id: '6', content: 'edbwebdwev ed we dvew dvwev dytwev cxyvew t' },
        { id: '7', content: 'edbwebdwev ed we dvew dvwev dytwev cxyvew t' },
        { id: '8', content: 'edbwebdwev ed we dvew dvwev dytwev cxyvew t' },
        { id: '9', content: 'edbwebdwev ed we dvew dvwev dytwev cxyvew t' },
        { id: '10', content: 'edbwebdwev ed we dvew dvwev dytwev cxyvew t' },
        { id: '11', content: 'edbwebdwev ed we dvew dvwev dytwev cxyvew t' },
        { id: '12', content: 'edbwebdwev ed we dvew dvwev dytwev cxyvew t' },
      ],
      orderIndex: '1',
      createdBy: {
        id: 'u1',
        firstName: 'Admin',
        lastName: 'User',
      },
      createdAt: new Date().toISOString(),
    },
    {
      id: '2',
      name: 'Jane Smith',
      email: 'jane@mail.com',
      phone: '+380000000001',
      status: 'in_progress',
      comment: 'Waiting for reply',
      orderIndex: '2',
      createdBy: {
        id: 'u1',
        firstName: 'Admin',
        lastName: 'User',
      },
      createdAt: new Date().toISOString(),
    },
    {
      id: '3',
      name: 'Michael Brown',
      email: 'michael@mail.com',
      phone: '+380000000002',
      status: 'done',
      comment: 'Deal closed',
      orderIndex: '3',

      createdBy: {
        id: 'u2',
        firstName: 'Sarah',
        lastName: 'Connor',
      },
      createdAt: new Date().toISOString(),
    },
    {
      id: '4',
      name: 'Emily Johnson',
      email: 'emily@mail.com',
      phone: '+380000000003',
      status: 'new',
      comment: 'Requested demo',
      orderIndex: '4',
      createdBy: {
        id: 'u2',
        firstName: 'Sarah',
        lastName: 'Connor',
      },
      createdAt: new Date().toISOString(),
    },
    {
      id: '5',
      name: 'Daniel Wilson',
      email: 'daniel@mail.com',
      phone: '+380000000004',
      status: 'in_progress',
      comment: 'Negotiation stage',
      orderIndex: '5',
      createdBy: {
        id: 'u3',
        firstName: 'Mike',
        lastName: 'Taylor',
      },
      createdAt: new Date().toISOString(),
    },
    {
      id: '6',
      name: 'Olivia Martinez',
      email: 'olivia@mail.com',
      phone: '+380000000005',
      status: 'new',
      comment: 'Left contact form',
      orderIndex: '6',
      createdBy: {
        id: 'u3',
        firstName: 'Mike',
        lastName: 'Taylor',
      },
      createdAt: new Date().toISOString(),
    },
    {
      id: '7',
      name: 'William Anderson',
      email: 'william@mail.com',
      phone: '+380000000006',
      status: 'done',
      comment: 'Signed contract',
      orderIndex: '7',
      createdBy: {
        id: 'u1',
        firstName: 'Admin',
        lastName: 'User',
      },
      createdAt: new Date().toISOString(),
    },
    {
      id: '8',
      name: 'Sophia Lee',
      email: 'sophia@mail.com',
      phone: '+380000000007',
      status: 'in_progress',
      comment: 'Preparing proposal',
      orderIndex: '8',
      createdBy: {
        id: 'u2',
        firstName: 'Sarah',
        lastName: 'Connor',
      },
      createdAt: new Date().toISOString(),
    },
    {
      id: '9',
      name: 'James Walker',
      email: 'james@mail.com',
      phone: '+380000000008',
      status: 'new',
      comment: 'Cold lead',
      orderIndex: '9',
      createdBy: {
        id: 'u3',
        firstName: 'Mike',
        lastName: 'Taylor',
      },
      createdAt: new Date().toISOString(),
    },
    {
      id: '10',
      name: 'Isabella Harris',
      email: 'isabella@mail.com',
      phone: '+380000000009',
      status: 'done',
      comment: 'Repeat client',
      orderIndex: '10',
      createdBy: {
        id: 'u1',
        firstName: 'Admin',
        lastName: 'User',
      },
      createdAt: new Date().toISOString(),
    },
    {
      id: '11',
      name: 'Benjamin Clark',
      email: 'ben@mail.com',
      phone: '+380000000010',
      status: 'in_progress',
      comment: 'Call scheduled',
      orderIndex: '11',
      createdBy: {
        id: 'u2',
        firstName: 'Sarah',
        lastName: 'Connor',
      },
      createdAt: new Date().toISOString(),
    },
    {
      id: '12',
      name: 'Mia Lewis',
      email: 'mia@mail.com',
      phone: '+380000000011',
      status: 'new',
      comment: 'Instagram lead',
      orderIndex: '12',
      createdBy: {
        id: 'u3',
        firstName: 'Mike',
        lastName: 'Taylor',
      },
      createdAt: new Date().toISOString(),
    },
    {
      id: '13',
      name: 'Lucas King',
      email: 'lucas@mail.com',
      phone: '+380000000012',
      status: 'done',
      comment: 'Upsell successful',
      orderIndex: '13',
      createdBy: {
        id: 'u1',
        firstName: 'Admin',
        lastName: 'User',
      },
      createdAt: new Date().toISOString(),
    },
    {
      id: '14',
      name: 'Charlotte Wright',
      email: 'charlotte@mail.com',
      phone: '+380000000013',
      status: 'in_progress',
      comment: 'Needs approval',
      orderIndex: '15',
      createdBy: {
        id: 'u2',
        firstName: 'Sarah',
        lastName: 'Connor',
      },
      createdAt: new Date().toISOString(),
    },
    {
      id: '15',
      name: 'Henry Scott',
      email: 'henry@mail.com',
      phone: '+380000000014',
      status: 'new',
      comment: 'Referred by partner',
      orderIndex: '16',
      createdBy: {
        id: 'u3',
        firstName: 'Mike',
        lastName: 'Taylor',
      },
      createdAt: new Date().toISOString(),
    },
  ])
}
